[package]
name = "emlop"
version = "0.5.0"
description = "A fast, accurate, ergonomic emerge.log parser"
keywords = ["gentoo", "portage", "emerge"]
categories = ["command-line-utilities", "parsing"]
readme = "README.md"
license = "GPL-3.0-only"
homepage = "https://github.com/vincentdephily/emlop"
repository = "https://github.com/vincentdephily/emlop"
authors = ["Vincent de Phily <moltonel@gmail.com>",
           "Illia Shestakov <ishestakov@airmail.cc>",
           "Alexis <flexibeast@gmail.com>"]
edition = "2021"
rust-version = "1.58.1"
exclude = ["/benches/*.log"]

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.32"
atty = "0.2.14"
clap = "2.33.3"
log = "0.4.11"
regex = "1.3.9"
sysconf = "~0.3"
crossbeam-channel = "0.5.0"
time = {version = "0.3.5", features = ["parsing", "formatting", "local-offset", "macros"]}
env_logger = {version = "0.9.0", default_features = false, features = ["termcolor", "atty"]}

[dev-dependencies]
assert_cmd = "2.0.4"
escargot = "0.5.0"
lazy_static = "1.4.0"

[profile.release]
debug = false
debug-assertions = false
codegen-units = 1
incremental = false
lto = true
panic = "abort"


