[package]
name = "emlop"
version = "0.6.1"
description = "A fast, accurate, ergonomic emerge.log parser"
keywords = ["gentoo", "portage", "emerge"]
categories = ["command-line-utilities", "parsing"]
readme = "README.md"
license = "GPL-3.0-only"
homepage = "https://github.com/vincentdephily/emlop"
repository = "https://github.com/vincentdephily/emlop"
authors = ["Vincent de Phily <moltonel@gmail.com>",
           "Illia Shestakov <ishestakov@airmail.cc>",
           "Alexis <flexibeast@gmail.com>"]
edition = "2021"
rust-version = "1.65.0"
exclude = ["benches", "docs", "rustfmt.toml", ".github", ".gitignore"]

[dependencies]
anyhow = "1.0.32"
atoi = "2.0.0"
# clap 4.4.0 has MSRV 1.70
clap = { version = "<4.4.0", features = ["cargo", "derive", "unstable-styles"] }
clap_complete = "~4.3.2"
# clap_lex 0.5.1 has MSRV 1.70
# Only used transitively, remove from Cargo.toml when our MSRV gets bumped
clap_lex = "<0.5.1"
crossbeam-channel = "0.5.0"
env_logger = { version = "0.10.0", default-features = false }
is-terminal = "0.4.9"
libc = { version = "0.2.126", default-features = false }
log = "0.4.11"
regex = { version = "1.3.9", default_features = false, features = ["std", "perf-inline", "perf-literal", "unicode-case"] }
rev_lines = "0.3.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
# time 0.3.24 has MSRV 1.67
time = {version = "<0.3.24", features = ["parsing", "formatting", "local-offset", "macros"]}

[dev-dependencies]
# assert_cmd 2.0.12 has MSRV 1.66
assert_cmd = "<2.0.12"

[[bench]]
# This is meant to be started directly, using scriptisto not cargo
name = "exec_compare"
bench = false

[features]
# Experimental features, may require nightly compiler.
# Currently only benchmarking.
unstable = []

[profile.release]
debug = false
debug-assertions = false
codegen-units = 1
incremental = false
lto = true
panic = "abort"
