[package]
name = "emlop"
version = "0.6.0"
description = "A fast, accurate, ergonomic emerge.log parser"
keywords = ["gentoo", "portage", "emerge"]
categories = ["command-line-utilities", "parsing"]
readme = "README.md"
license = "GPL-3.0-only"
homepage = "https://github.com/vincentdephily/emlop"
repository = "https://github.com/vincentdephily/emlop"
authors = ["Vincent de Phily <moltonel@gmail.com>",
           "Illia Shestakov <ishestakov@airmail.cc>",
           "Alexis <flexibeast@gmail.com>"]
edition = "2021"
rust-version = "1.65.0"
exclude = ["/benches/*.log"]

[dependencies]
anyhow = "1.0.32"
atoi = "2.0.0"
atty = "0.2.14"
clap = { version = "3.1.15", default_features = false, features = ["cargo", "color", "suggestions", "derive"] }
clap_complete = "3.1.4"
crossbeam-channel = "0.5.0"
env_logger = { version = "0.10.0", default-features = false }
libc = { version = "0.2.126", default-features = false }
log = "0.4.11"
regex = { version = "1.3.9", default_features = false, features = ["std", "perf-inline", "perf-literal", "unicode-case"] }
rev_lines = "0.2.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
time = {version = "0.3.5", features = ["parsing", "formatting", "local-offset", "macros"]}

[dev-dependencies]
assert_cmd = "2.0.4"
escargot = "0.5.0"
lazy_static = "1.4.0"

[profile.release]
debug = false
debug-assertions = false
codegen-units = 1
incremental = false
lto = true
panic = "abort"


