name: Security audit

on:
  schedule:
    # Runs at 07:00 UTC every monday
    - cron: '7 0 * * 1'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/audit.yml'
      - '**/audit.toml'
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/audit@v1

