name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        obj:
          # Base
          - toolchain: stable
            timezone: UTC
            target: x86_64-unknown-linux-gnu
          # Timezones
          - toolchain: stable
            timezone: Europe/Dublin
            target: x86_64-unknown-linux-gnu
          - toolchain: stable
            timezone: Canada/Newfoundland
            target: x86_64-unknown-linux-gnu
          - toolchain: stable
            timezone: Pacific/Kiritimati
            target: x86_64-unknown-linux-gnu
          # MSRV
          - toolchain: 1.74.1
            timezone: UTC
            target: x86_64-unknown-linux-gnu
          # Targets
          - toolchain: stable
            timezone: UTC
            target: i686-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.obj.toolchain }}
          target: ${{ matrix.obj.target }}
      - run: cargo test --target ${{ matrix.obj.target }} -- --include-ignored
        env:
          TZ: ${{ matrix.obj.timezone }}

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Check formatting
        uses: actions-rust-lang/rustfmt@v1

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy -- -D warnings
