name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [1.74.1, stable]
        include:
          - timezone: UTC
            target: x86_64-unknown-linux-gnu
          - timezone: Europe/Dublin
            toolchain: stable
          - timezone: Canada/Newfoundland
            toolchain: stable
          - timezone: Pacific/Kiritimati
            toolchain: stable
          - target: i586-unknown-linux-gnu
            toolchain: stable
          - target: i686-unknown-linux-musl
            toolchain: stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
      - run: cargo test --target ${{ matrix.target }} -- --include-ignored
        env:
          TZ: ${{ matrix.timezone }}

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Check formatting
        uses: actions-rust-lang/rustfmt@v1

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy -- -D warnings
